const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
const UPDATE_USER_DATA = "UPDATE_USER_DATA";
const POPULATE_CATEGORIES = "POPULATE_CATEGORIES";
const POPULATE_PRODUCTS = "POPULATE_PRODUCTS";

export {
  CHANGE_LOGIN_STATUS,
  UPDATE_USER_DATA,
  POPULATE_CATEGORIES,
  POPULATE_PRODUCTS,
};
